// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"

struct FileHistory; 

struct History_;

struct History {
    obx_id id;
    int64_t date;
    uint32_t total_files;
    uint32_t status;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 2; }
    
        static void setObjectId(History& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const History& object);
    
        /// Read an object from a valid FlatBuffer
        static History fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<History> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, History& outObject);
    };
};

struct History_ {
    static const obx::Property<History, OBXPropertyType_Long> id;
    static const obx::Property<History, OBXPropertyType_Date> date;
    static const obx::Property<History, OBXPropertyType_Int> total_files;
    static const obx::Property<History, OBXPropertyType_Int> status;
    static const obx::RelationStandalone<History, FileHistory> files;
};


struct Profile_;

struct Profile {
    obx_id id;
    std::string full_name;
    std::string avatar_path;
    int32_t role;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 3; }
    
        static void setObjectId(Profile& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Profile& object);
    
        /// Read an object from a valid FlatBuffer
        static Profile fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Profile> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Profile& outObject);
    };
};

struct Profile_ {
    static const obx::Property<Profile, OBXPropertyType_Long> id;
    static const obx::Property<Profile, OBXPropertyType_String> full_name;
    static const obx::Property<Profile, OBXPropertyType_String> avatar_path;
    static const obx::Property<Profile, OBXPropertyType_Int> role;
};

struct Profile; 

struct User_;

struct User {
    obx_id id;
    std::string username;
    std::string password;
    bool is_admin;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 4; }
    
        static void setObjectId(User& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const User& object);
    
        /// Read an object from a valid FlatBuffer
        static User fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<User> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, User& outObject);
    };
};

struct User_ {
    static const obx::Property<User, OBXPropertyType_Long> id;
    static const obx::Property<User, OBXPropertyType_String> username;
    static const obx::Property<User, OBXPropertyType_String> password;
    static const obx::Property<User, OBXPropertyType_Bool> is_admin;
    static const obx::RelationStandalone<User, Profile> profile;
};


struct FileHistory_;

struct FileHistory {
    obx_id id;
    std::string filename;
    int64_t date_created;
    int64_t date_modified;
    float confidence_score;
    uint32_t file_size;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 5; }
    
        static void setObjectId(FileHistory& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const FileHistory& object);
    
        /// Read an object from a valid FlatBuffer
        static FileHistory fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<FileHistory> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, FileHistory& outObject);
    };
};

struct FileHistory_ {
    static const obx::Property<FileHistory, OBXPropertyType_Long> id;
    static const obx::Property<FileHistory, OBXPropertyType_String> filename;
    static const obx::Property<FileHistory, OBXPropertyType_Long> date_created;
    static const obx::Property<FileHistory, OBXPropertyType_Long> date_modified;
    static const obx::Property<FileHistory, OBXPropertyType_Float> confidence_score;
    static const obx::Property<FileHistory, OBXPropertyType_Int> file_size;
};

