// Code generated by ObjectBox; DO NOT EDIT.

#include "model.obx.hpp"

const obx::Property<History, OBXPropertyType_Long> History_::id(1);
const obx::Property<History, OBXPropertyType_Date> History_::date(2);
const obx::Property<History, OBXPropertyType_Int> History_::total_files(3);
const obx::Property<History, OBXPropertyType_Int> History_::status(4);
const obx::RelationProperty<History, User> History_::user_id(5);

void History::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const History& object) {
    fbb.Clear();
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.date);
    fbb.AddElement(8, object.total_files);
    fbb.AddElement(10, object.status);
    fbb.AddElement(12, object.user_id);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

History History::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    History object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<History> History::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<History>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void History::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, History& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.date = table->GetField<int64_t>(6, 0);
    outObject.total_files = table->GetField<uint32_t>(8, 0);
    outObject.status = table->GetField<uint32_t>(10, 0);
    outObject.user_id = table->GetField<obx_id>(12, 0);
}

const obx::Property<Profile, OBXPropertyType_Long> Profile_::id(1);
const obx::Property<Profile, OBXPropertyType_String> Profile_::full_name(2);
const obx::Property<Profile, OBXPropertyType_String> Profile_::avatar_path(3);
const obx::Property<Profile, OBXPropertyType_Int> Profile_::role(4);

void Profile::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Profile& object) {
    fbb.Clear();
    auto offsetfull_name = fbb.CreateString(object.full_name);
    auto offsetavatar_path = fbb.CreateString(object.avatar_path);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetfull_name);
    fbb.AddOffset(8, offsetavatar_path);
    fbb.AddElement(10, object.role);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Profile Profile::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Profile object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Profile> Profile::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Profile>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Profile::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Profile& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.full_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.full_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.avatar_path.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.avatar_path.clear();
        }
    }
    outObject.role = table->GetField<int32_t>(10, 0);
}

const obx::Property<User, OBXPropertyType_Long> User_::id(1);
const obx::Property<User, OBXPropertyType_String> User_::username(2);
const obx::Property<User, OBXPropertyType_String> User_::password(3);
const obx::Property<User, OBXPropertyType_Bool> User_::is_admin(5);
const obx::RelationProperty<User, Profile> User_::profile_id(6);

void User::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const User& object) {
    fbb.Clear();
    auto offsetusername = fbb.CreateString(object.username);
    auto offsetpassword = fbb.CreateString(object.password);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetusername);
    fbb.AddOffset(8, offsetpassword);
    fbb.AddElement(12, object.is_admin ? 1 : 0);
    fbb.AddElement(14, object.profile_id);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

User User::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    User object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<User> User::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<User>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void User::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, User& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.username.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.username.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.password.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.password.clear();
        }
    }
    outObject.is_admin = table->GetField<uint8_t>(12, 0) != 0;
    outObject.profile_id = table->GetField<obx_id>(14, 0);
}

const obx::Property<FileHistory, OBXPropertyType_Long> FileHistory_::id(1);
const obx::Property<FileHistory, OBXPropertyType_String> FileHistory_::filename(2);
const obx::Property<FileHistory, OBXPropertyType_Date> FileHistory_::date_created(3);
const obx::Property<FileHistory, OBXPropertyType_Long> FileHistory_::date_modified(4);
const obx::Property<FileHistory, OBXPropertyType_Float> FileHistory_::confidence_score(5);
const obx::Property<FileHistory, OBXPropertyType_Int> FileHistory_::file_size(6);
const obx::RelationProperty<FileHistory, History> FileHistory_::history_id(7);

void FileHistory::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const FileHistory& object) {
    fbb.Clear();
    auto offsetfilename = fbb.CreateString(object.filename);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetfilename);
    fbb.AddElement(8, object.date_created);
    fbb.AddElement(10, object.date_modified);
    fbb.AddElement(12, object.confidence_score);
    fbb.AddElement(14, object.file_size);
    fbb.AddElement(16, object.history_id);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

FileHistory FileHistory::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    FileHistory object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<FileHistory> FileHistory::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<FileHistory>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void FileHistory::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, FileHistory& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.filename.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.filename.clear();
        }
    }
    outObject.date_created = table->GetField<int64_t>(8, 0);
    outObject.date_modified = table->GetField<int64_t>(10, 0);
    outObject.confidence_score = table->GetField<float>(12, 0.0f);
    outObject.file_size = table->GetField<uint32_t>(14, 0);
    outObject.history_id = table->GetField<obx_id>(16, 0);
}

