
namespace LeafEyeCore
{
    enum UserRole
    {
        Admin = 0,
        User = 1
    };
    
    [default_interface]
    runtimeclass UserRoleHelper
    {
        UserRoleHelper();
        static String ConvertUserRoleToString(UserRole role);
        static String ConvertUserIntRoleToString(Int32 role);
    }

}