namespace LeafEye
{
    [default_interface]
    runtimeclass AddUserDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        AddUserDialog();
        
        String Username{ get; };
        String Password{ get; };
        Boolean IsAdmin{ get; };

        void ShowMessage(String message, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);

    }
}