namespace LeafEye
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();
        
        LeafEyeCore.ProfileModel Profile{set;get;};
        String MyStatusText;
        void DismissOverlay();
        void Logout();

    }
}
