namespace LeafEye
{
    [default_interface]
    runtimeclass ProfilePage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ProfilePage();
        LeafEyeCore.ProfileModel Profile{ get; };
        LeafEyeCore.UserModel User{ get; };
        static String GetUserNameAndFullNameString(String username, String fullname);

        Boolean IsChanged{get;set;};
    }
}
