namespace LeafEye
{
    [default_interface]
    runtimeclass UpdateUserDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        UpdateUserDialog();

        void SetUserData(String username, Boolean isAdmin);

        String Username();
        String Password();
        Boolean IsAdmin();
    }
}