namespace LeafEye
{
    [default_interface]
    runtimeclass UsersPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UsersPage();
        static String ConvertToUserStatus(Boolean is_admin);
        
        String GetPaginationInfo{get;};
        Int64 TotalPage{set;get;};
        Int64 CurrentPage{get;set;};
        Boolean PrevPageEnabled{set;get;};
        Boolean NextPageEnabled{set;get;};

    }
}
